# Generated by Django 5.0 on 2023-12-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stix_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stixbundle',
            name='bundle_json',
            field=models.TextField(),
        ),
    ]
